### ISSUE TITLE
Upload to rebrickable

### ISSUE THREAD

**Issue by quizilkend** [tobetz/LegoMicroscope#1]
Hey there,

wonderful project!

As my children have their lego already tracked on rebrickable, I was wondering if you could upload the microscope there too.

That would enable us to buy only the parts that are missing right now to build the microscope.

You could submit the microscope as MOC and also upload the PDF-Instructions there.

Best regards!
Samuel

**Comment by tobetz** [comment]
Thanks Samuel,

I have to admit that I don't have enough experience with rebrickable. I will take a look and update the site if I manage to submit it there. 

best,
Timo

**Comment by quizilkend** [comment]
Hi Timo,
thanks. That would be awesome!
Best regards,
Samuel

**Comment by tobetz** [comment]
I just got the acceptance for the MOC from Rebrickable. You can find it at:
[https://rebrickable.com/mocs/MOC-74344/tobetz/lego-microscope/#details](https://rebrickable.com/mocs/MOC-74344/tobetz/lego-microscope/#details)
I will close the issue.
