### ISSUE TITLE
Lens option from China 

### ISSUE THREAD

**Issue by XiT999** [tobetz/LegoMicroscope#13]
Hi Prof. Timo, hola from Xi.

Here is my lens options in China,

iPhone 5s replacement camera, f=4.1mm 
Acrylic lens (2x) ：(diameter 31.5 mm, f = 100mm)
Glass lens：(diameter 17.5 mm, f = 25 mm)

The distance between the object and the second lens was measured with a ruler and found to be 237 mm, so at last, according to the formula, we got the total high-magnification M = 217X, total low-magnification of M = 26X.
Still hope it's right.

We took some videos to explain the process, here is the link: 
Lens Part：https://www.youtube.com/watch?v=eeqykJiaFA4
Reduced distance：https://www.youtube.com/watch?v=ak24DZypnQc
LED Replaced：https://www.youtube.com/watch?v=r31mmgsWXp0
Results：https://www.youtube.com/watch?v=3H98Z7Qradw

Chinese text via https://mp.weixin.qq.com/s/8inIznvt7qHr4usf3euMQw

**Comment by tobetz** [comment]
Dear Xi,

thanks a lot for the input! And especially for the videos to explain the details!

best,
Timo
