### ISSUE TITLE
3d printed option

### ISSUE THREAD

**Issue by brussli1** [tobetz/LegoMicroscope#14]
Any way i can help designing a 3d printed version of this?. As brick by brick but also just to be able to print a microscope.

**Comment by tobetz** [comment]
Hi Brussli1,

If you want to do this, I think you should really sit back and think. It is a great idea, but you need to know what you aim at. Do you want it for kids? Do you want it to be simple? Do you want it flexible? 
3D printing is amazing, and opens so many doors... you need to know which door you want to step through. We wanted to get a simple instruments kids can play with, and that does not need a 3D printer or high end optics. 
A 3D printed version could do many different things. Decide what you would like to get :-)

best,
Timo

**Comment by brussli1** [comment]
Thanks Timo,
I just want to print a microscope for the kid of my girlfriend! I don't know a lot about microscopes but i know about building! Any guides you would recommend me to get more in depth in this topic?.

**Comment by tobetz** [comment]
Hi Brussli1,

I see.... Well there are some cool 3D printed options out there. But they often are designed to work with a cellphone or a raspberry pi. You may want to take a look at: 
https://www.instructables.com/3D-printable-microscope-for-home-or-lab/
Lenses you can also get from Edmund Scientific. You might need to adjust the distances for the lenses you can get, but if you print it anyway there is no problem. 
They also provide the files for the printing. 

Good luck,
best,
Timo

**Comment by brussli1** [comment]
Thanks Timo, will check it out. Luckyly i already have a RPi laying around.
