### ISSUE TITLE
how to remove the iphone lens, and which way up to mount it?

### ISSUE THREAD

**Issue by aardvarkkrill** [tobetz/LegoMicroscope#15]
I'm an adult, and have lots of sharp tools, but I can't see how to remove this lens without risking damaging it.  And then, if I remove it, which way up to insert it?  I've been through all the materials, as far as I can see, but not much help is there for the non-lego bits.  thanks.

**Comment by CyberDziubi** [comment]
You can use scissors to open up the case, maybe with a little support by a pincer. The metal is quite weak and can be bent as far as needed. The lens has to be installed with the smaller hole facing upwards. It also has to be very close to the object plate.

**Comment by aardvarkkrill** [comment]
Thank you!  I managed to get it apart as you said.  Solved.
