### ISSUE TITLE
eyepiece lens

### ISSUE THREAD

**Issue by aardvarkkrill** [tobetz/LegoMicroscope#16]
"Ocular: We used two simple acrylic lens (diameter 34.5 mm, f = 106 mm) as occular, which we combined using simple transparent tape. In the current setup we use the lens number 308.OM7."

I bought two plastic OM-7 lenses, as suggested for the eyepiece.  How do I use them both?  What does "combined" mean -- is the transparent tape on the optical path?  Which way round should the lenses go, out of the 4 possibilities?  Thanks!

**Comment by CyberDziubi** [comment]
The two OM-7 lenses have to be combined to a biconvex lens. So, the top-lense curvature has to face up and the bottom-lens curvature has to face downwards.

**Comment by aardvarkkrill** [comment]
Thanks again!
