### ISSUE TITLE
Alternative supplier lens

### ISSUE THREAD

**Issue by fryper** [tobetz/LegoMicroscope#18]
Thanks to the great succes of your project the  low-magnification objective lens of Astromedia is sold out (and it will stay so).
Are there alternatives ?
While i am here, Is it right that the i-phone lens is not straight under the occular lens?

**Comment by tobetz** [comment]
It should be sufficiently precise to see the image. if this is not the case, you should play a mit around with the mounting of the iPhone lens. 

Regarding the lenses. There are alternatives from Edmund. I discussed this in another issue [here](https://github.com/tobetz/LegoMicroscope/issues/9)
