### ISSUE TITLE
question about alignment of lenses

### ISSUE THREAD

**Issue by aardvarkkrill** [tobetz/LegoMicroscope#19]
Hi, I am trying to improve some of the (already amazing!) design.  
I noticed in Lego plans that the eyepiece isn't directly above the centre of the objective, and not directly above the LED.  Is this for eye safety?  Should they all line up exactly?
thanks again.

**Comment by tobetz** [comment]
You are right, it's not perfect. We were trying a lot of different ways, but there is a slight mismatch. This is the reason why you need to move the eye a bit to view the image. 
It's not to protect the eyes, as in the current setup the LED is not that powerful. The higher the magnification the lower the light that enters the eye, as you see a smaller area of the LED.

Please feel free to play with the mounting of the objectives. If you find a better way than what we have, you are inivited to update the plan that we put online. I would be happy to include your solution.

best
